# Generated by Django 4.2.3 on 2024-01-04 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='finish',
        ),
        migrations.CreateModel(
            name='Valid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField()),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('asked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxo.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
