# Generated by Django 4.2.3 on 2024-01-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxo', '0004_ideapic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ImageField(upload_to='idea')),
                ('back', models.ImageField(upload_to='back')),
            ],
        ),
        migrations.DeleteModel(
            name='IdeaPic',
        ),
    ]
