# Generated by Django 4.2.3 on 2024-01-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxo', '0006_useful_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='useful',
            name='title',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
